apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-task
spec:
  replicas: 1
  selector:
    matchLabels:
        app: multi-task
  template:
    metadata:
      labels:
        app: multi-task
    spec:
      containers:
      - name: multi-task
        image: dayanak/multi-task
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
